name: CI/CD Pipeline

on:
  push:
    branches: [ test_branch1, ]
  pull_request:
    branches: [ test_branch1 ]

jobs:
  build:
    runs-on: ubuntu-latest  # Runs in a fresh Linux container

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven on GitHub Runner
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Verify Maven Installation
        run: mvn -version

      - name: Check File Structure
        run: ls -R  # This will list all files & help debug missing files

      - name: Build Backend
        working-directory: backend
        run: mvn clean package
