name: " AI Run Code Review"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Set up Java"
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: "Build Backend"
        run: |
          cd backend
          mvn clean package

      - name: "Run Code Review"
        run: |
          cd backend
          java -jar target/backend-0.0.1-SNAPSHOT.jar --spring.profiles.active=ci &  
          sleep 20


      - name: "Check if backend is running"
        run: curl http://localhost:8080/review || echo "Backend not responding"

      - name: "Post GitHub Comment"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:8080/review -H "Content-Type: application/vnd.spring-boot.actuator.v3+json" \
            -d '{"repository": "'"${REPO}"'", "commitId": "dummy-commit", "code": "print(eval(\"2+2\"))"}')
      
          echo "🔍 Backend Response: ${RESPONSE}"  # Debugging: Print API response
      
          COMMENT_BODY=$(echo "${RESPONSE}" | jq -r '.suggestions | join("\n")' || echo "Error: API request failed")
          
          echo "📝 COMMENT_BODY=${COMMENT_BODY}"  # Debugging: Print parsed comment
      
          if [ -z "$COMMENT_BODY" ] || [ "$COMMENT_BODY" == "Error: API request failed" ]; then
            echo "❌ API request to backend failed. Exiting."
            exit 1
          fi
      
          curl -H "Authorization: token ${GITHUB_TOKEN}" \
               -X POST \
               -d "{\"body\": \"AI Code Review Results:\n\n${COMMENT_BODY}\"}" \
               https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments
      